### ISSUE TITLE
scratch issue for miscellanea DO NOT DELETE

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/MIT-MUQ#2]
## Building MUQ libs
```
cmake -DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DMUQ_USE_GTEST=ON \
-DCMAKE_INSTALL_PREFIX=$PWD/../install -S ../ -B ./
```

## Building MUQ examples

```
export MUQ_DIR=/path/to/MUQ/build
./BuildAllExamples.sh
```

---------------

## Things found along the way 

- setting cmake flags for apple silicon architecture

**Comment by pierrepebay** [comment]
### GTest Version
---
The standard required by MUQ being C++11, GTest has to be downgraded to an older version; the last GTest release that does not require a standard higher than C++11 is v1.12.1.
![image](https://github.com/NexGenAnalytics/MIT-MUQ/assets/68857547/c85f5f7e-0893-468a-8fab-2fe9a43988f4)
